apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test03-nfs-pvc 
  labels:
    nfs: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
#  storageClassName: youngjin-nfs-without-fileshare-sc 

