apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-test
  labels:
    app: mario-test
  namespace: mario
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mario-test
  template:
    metadata:
      labels:
        app: mario-test
    spec:
      containers:
      - name: mario-test
        image: pengbai/docker-supermario

