apiVersion: v1
kind: Service
metadata:
  name: mario-test
  namespace: mario
spec:
  selector:
    app: mario-test
  ports:
  type: NodePort
  ports:
   -  port: 80
      targetPort: 8080
#      nodePort: 30007