apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario
  labels:
    app: mario
  namespace: mario
spec:
  # replicas: 4
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario
        image: harbor.io/library/mario:1.1
        name: mario
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 50m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  # creationTimestamp: "2023-01-04T02:12:01Z"
  name: mario
  namespace: mario
  # resourceVersion: "16615968"
  # uid: 9d49c48a-3b68-473c-bac6-954fbcefd976
spec:
  maxReplicas: 7
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 30
        type: Utilization
    type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mario


