apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-sc-test
  labels:
    app: tetris-sc-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris-sc-test
  template:
    metadata:
      labels:
        app: tetris-sc-test
    spec:
      containers:
      - name: tetris-sc-test
        image: bsord/tetris
        volumeMounts:
        - name: rwopath
          mountPath: /nfs/test
      volumes:
      - name: rwopath
        persistentVolumeClaim:
          claimName: elastic-sc2
      
---
apiVersion: v1
kind: Service
metadata:
  name: tetris-sc-test
spec:
  externalTrafficPolicy: Cluster 
  selector:
    app: tetris-sc-test
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
