apiVersion: v1
kind: ConfigMap
metadata:
  name: yj-ha-mysql
  labels:
    app: yj-ha-mysql
    app.kubernetes.io/name: mysql
data:
  primary.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    log-bin    
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    super-read-only    



