apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-rwx
  labels:
    app: tetris
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris
        image: bsord/tetris
        volumeMounts:
        - name: jypath
          mountPath: /nfs/test
      volumes:
      - name: jypath
        persistentVolumeClaim:
          claimName: test03-nfs-pvc 

---
apiVersion: v1
kind: Service
metadata:
  name: tetris-rwx
spec:
  externalTrafficPolicy: Local
  selector:
    app: tetris
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30022

