apiVersion: v1
kind: Service
metadata:
  name: tetris
  namespace: tetris
spec:
  externalTrafficPolicy: Cluster 
  selector:
    app: tetris
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
