apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: yj-ha-mysql-sc
provisioner: csi.vsphere.vmware.com
parameters:
  storagepolicyname: "k8s Storage Policy"
#리클레임 폴리시
reclaimPolicy: Delete
