apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youngjin-rwx-without-fileshare-pvc 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: youngjin-nfs-without-fileshare-sc 

