apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-mysql-rwo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
        containers:
        - image: docker.io/library/mysql
          #imagePullPolicy: Never  #Do not use remote mirror
          name: mysql
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
          volumeMounts:
          - name: mysql-rwo
            mountPath: /var/lib/mysql
        volumes:
        - name: mysql-rwo
          persistentVolumeClaim:
            claimName: k8s-rwo-pvc
            
