apiVersion: v1
kind: Service
metadata:
  name: myweb
spec:
  ports:
  - name: myweb-svc
    port: 8080 #Port number of the Service
    targetPort: 8080  #Port number of container exposed
    nodePort: 30001  #The real port number of the node
  selector:
    app: myweb   #Service selected pod with tag app: myweb
  type: NodePort

