# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: yj-ha-mysql
  labels:
    app: yj-ha-mysql
    app.kubernetes.io/name: mysql
spec:
  ports:
  - name: yj-ha-mysql
    port: 3306
  clusterIP: None
  selector:
    app: yj-ha-mysql
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the primary: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: yj-ha-mysql-read
  labels:
    app: yj-ha-mysql
    app.kubernetes.io/name: mysql
    readonly: "true"
spec:
  ports:
  - name: yj-ha-mysql
    port: 3306
  selector:
    app: yj-ha-mysql

