apiVersion: v1
kind: Service
metadata:
  name: yj-ha-tomcat
spec:
  ports:
  - name: yj-ha-tomcat
    port: 8080 #Port number of the Service
    targetPort: 8080  #Port number of container exposed
    nodePort: 30017  #The real port number of the node
  selector:
    app: yj-ha-tomcat   #Service selected pod with tag app: yj-ha-tomcat
  type: NodePort

