apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-default
  labels:
    app: mario-default
  namespace: ingress-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mario-default
  template:
    metadata:
      labels:
        app: mario-default
    spec:
      containers:
      - name: mario
        image: pengbai/docker-supermario
---
apiVersion: v1
kind: Service
metadata:
  name: mario-default
  namespace: ingress-nginx
spec:
  selector:
    app: mario-default
  ports:
  type: NodePort 
  ports:
   -  port: 80
      targetPort: 8080
      nodePort: 31234
