# # apiVersion: autoscaling/v2
# # kind: HorizontalPodAutoscaler
# # metadata:
# #   name: mario
# #   namespace: mario
# # spec:
# #   maxReplicas: 10
# #   metrics:
# #   - resource:
# #       name: cpu
# #       target:
# #         averageUtilization: 30
# #         type: Utilization
# #     type: Resource
# #   minReplicas: 1
# #   scaleTargetRef:
# #     apiVersion: apps/v1
# #     kind: Deployment
# #     name: mario
# apiVersion: v1
# items:
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  # creationTimestamp: "2023-01-04T02:12:01Z"
  name: mario
  namespace: mario
  # resourceVersion: "16615968"
  # uid: 9d49c48a-3b68-473c-bac6-954fbcefd976
spec:
  maxReplicas: 15
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 30
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mario
  # status:
  #   conditions:
  #   - lastTransitionTime: "2023-01-04T02:12:16Z"
  #     message: recent recommendations were higher than current one, applying the highest
  #       recent recommendation
  #     reason: ScaleDownStabilized
  #     status: "True"
  #     type: AbleToScale
  #   - lastTransitionTime: "2023-01-04T02:12:31Z"
  #     message: the HPA was able to successfully calculate a replica count from cpu
  #       resource utilization (percentage of request)
  #     reason: ValidMetricFound
  #     status: "True"
  #     type: ScalingActive
  #   - lastTransitionTime: "2023-01-04T02:19:46Z"
  #     message: the desired replica count is less than the minimum replica count
  #     reason: TooFewReplicas
  #     status: "True"
  #     type: ScalingLimited
  #   currentMetrics:
  #   - resource:
  #       current:
  #         averageUtilization: 3
  #         averageValue: 1m
  #       name: cpu
  #     type: Resource
  #   currentReplicas: 3
  #   desiredReplicas: 3
  #   lastScaleTime: "2023-01-04T02:19:46Z"
# kind: List
# metadata:
#   resourceVersion: ""